<?php
/**
 * PharmaSync - global configuration. Group 46.
 *
 * Do NOT edit this file for your own machine. BASE_URL is detected
 * automatically, so the project runs from any folder name inside htdocs.
 * If something here is wrong, it is wrong for everyone - tell the group.
 */

date_default_timezone_set('Asia/Colombo');

/* ==========================================================================
   1. Paths
   ========================================================================== */
define('ROOT_PATH',    dirname(__DIR__));
define('APP_PATH',     ROOT_PATH . '/app');
define('CONFIG_PATH',  ROOT_PATH . '/config');
define('PUBLIC_PATH',  ROOT_PATH . '/public');
define('LIB_PATH',     ROOT_PATH . '/lib');

/*
 * Uploaded prescriptions live OUTSIDE public/ so nobody can fetch one by
 * guessing its URL. They are served by a controller that checks ownership.
 */
define('STORAGE_PATH',            ROOT_PATH . '/storage');
define('PRESCRIPTION_UPLOAD_DIR', STORAGE_PATH . '/prescriptions/');

/*
 * Accounts file used by app/models/User.php while DB_ENABLED is false.
 * Created on first login with one demo account per role. Git-ignored.
 */
define('USERS_STORE_FILE', STORAGE_PATH . '/users.json');

/* ==========================================================================
   2. Base URL (auto-detected - nobody edits this)
   ==========================================================================
   Works for:
     http://localhost/PharmaSync/public
     http://localhost/pharmasync-group46/public
     http://pharmasync.test
*/
$protocol  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host      = $_SERVER['HTTP_HOST'] ?? 'localhost';
$scriptDir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? ''));
$scriptDir = ($scriptDir === '/' || $scriptDir === '.') ? '' : $scriptDir;

define('BASE_URL', $protocol . '://' . $host . rtrim($scriptDir, '/'));

/* ==========================================================================
   3. Roles - the single source of truth for role naming
   ==========================================================================
   Three spellings exist and each has a job. Never type one by hand.

     1. DATABASE value   users.role ENUM     'Inventory_Manager'
     2. URL segment      /InventoryManager/  'InventoryManager'
     3. ASSET folder     assets/css/<dir>/   'InventoryManager'

   Controller and model files are FLAT in app/controllers and app/models
   (this matches the GitHub repo). Files are prefixed with the role instead:
     CustomerCartController.php, PharmacistQueueController.php, ...
   Views and stylesheets are the parts split into role folders.
   -------------------------------------------------------------------------- */

/** Database ENUM value -> URL segment. */
define('ROLE_SLUGS', [
    'Customer'          => 'customer',
    'Pharmacist'        => 'pharmacist',
    'Admin'             => 'admin',
    'Inventory_Manager' => 'InventoryManager',
    'Delivery_Partner'  => 'deliveryPartner',
]);

/** Reverse map: URL segment -> database ENUM value. */
define('SLUG_ROLES', array_flip(ROLE_SLUGS));

/** Lowercased index, used by the router so /customer and /Customer both work. */
define('ROLE_SLUG_LOOKUP', array_change_key_case(SLUG_ROLES, CASE_LOWER));

/** View folder per role: app/views/<folder>/ */
define('ROLE_VIEW_DIRS', [
    'Customer'          => 'customer',
    'Pharmacist'        => 'pharmacist',
    'Admin'             => 'admin',
    'Inventory_Manager' => 'InventoryManager',
    'Delivery_Partner'  => 'deliveryPartner',
]);

/** Stylesheet folder per role: public/assets/css/<folder>/ - PascalCase for all five. */
define('ROLE_ASSET_DIRS', [
    'Customer'          => 'Customer',
    'Pharmacist'        => 'Pharmacist',
    'Admin'             => 'Admin',
    'Inventory_Manager' => 'InventoryManager',
    'Delivery_Partner'  => 'DeliveryPartner',
]);

/** Login, registration and logout are not a role, so they get their own segment. */
define('AUTH_SLUG', 'authentication');

/* ==========================================================================
   4. Database
   ==========================================================================
   DB_ENABLED stays false until the schema is imported and the models are
   switched over. While it is false, Model::db() returns null and each
   module serves its own sample data from the session.
*/
define('DB_HOST',    'localhost');
define('DB_NAME',    'pharmasync');
define('DB_USER',    'root');
define('DB_PASS',    '');            // default XAMPP root has no password
define('DB_CHARSET', 'utf8mb4');
define('DB_ENABLED', false);

/*
 * MySQL for the customer CRUD only (family members, their allergies and
 * conditions, saved addresses) and the accounts they belong to. Everything
 * else keeps using sample data. Import
 * database/003_add_customer_profile_tables.sql first, then set this to true.
 */
define('CUSTOMER_DB_ENABLED', true);

/*
 * Sample data lives in the session until DB_ENABLED is true, and each model
 * only seeds when its session key is empty. An old browser session therefore
 * keeps serving data in the OLD shape after a seed changes.
 *
 * Bump this number whenever you change the shape of any seed array. Sessions
 * on an older number are re-seeded on their next request. Delete once every
 * model reads from MySQL.
 */
define('SEED_VERSION', 3);

/*
 * The account the customer sample data (orders, prescriptions, family,
 * addresses) belongs to - customer@pharmasync.com in the demo accounts.
 * Other accounts start with an empty module.
 */
define('DEMO_CUSTOMER_ID', 1);

/*
 * Session keys that get cleared when SEED_VERSION changes. Add your own
 * module's keys here. 'user' and 'csrf_token' are deliberately NOT in this
 * list, so a re-seed never signs anyone out or breaks an open form.
 */
define('SEEDED_SESSION_KEYS', [
    // customer
    'orders', 'prescriptions', 'family_members', 'addresses', 'notifications',
    'cart', 'saved_for_later', 'promo_code', 'recently_viewed',
    'reorder_prescription_id',
    // pharmacist / admin / inventory / delivery - add yours below
]);

/* ==========================================================================
   5. Uploads
   ========================================================================== */
define('PRESCRIPTION_MAX_SIZE',      5 * 1024 * 1024);   // 5 MB
define('PRESCRIPTION_ALLOWED_TYPES', ['image/jpeg', 'image/png', 'application/pdf']);
define('PRESCRIPTION_MIME_EXT', [
    'image/jpeg'      => 'jpg',
    'image/png'       => 'png',
    'application/pdf' => 'pdf',
]);

/** Medicine photos and other images that ARE served straight from public/. */
define('MAX_UPLOAD_BYTES',   5 * 1024 * 1024);
define('ALLOWED_IMAGE_MIME', ['image/jpeg', 'image/png', 'image/webp']);

/* ==========================================================================
   6. Business rules (shared - pharmacist and delivery read these too)
   ========================================================================== */
define('DELIVERY_FEE', 150.00);
define('TAX_RATE',     0.02);
define('CURRENCY',     'Rs.');

/* Store pickup (single branch) */
define('STORE_NAME',    'PharmaSync Pharmacy - Colombo');
define('STORE_ADDRESS', '12 Galle Road, Colombo 03');
define('STORE_PHONE',   '+94 11 234 5678');
define('STORE_HOURS',   'Mon-Sat 8:00 AM - 8:00 PM | Sun 9:00 AM - 5:00 PM');
define('STORE_PICKUP_HOURS',      [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]); // Mon-Sat
define('STORE_PICKUP_HOURS_SUN',  [9, 10, 11, 12, 13, 14, 15, 16]);             // Sunday
define('STORE_PICKUP_PREP_HOURS', 2);

/* ==========================================================================
   7. Mail
   ==========================================================================
   Mailer::send() is a no-op while MAIL_ENABLED is false, so no page ever
   hangs waiting for SMTP during development.
*/
define('MAIL_ENABLED',   false);
define('MAIL_HOST',      'smtp.example.com');
define('MAIL_PORT',      587);
define('MAIL_USERNAME',  'no-reply@pharmasync.test');
define('MAIL_PASSWORD',  '');
define('MAIL_FROM',      'no-reply@pharmasync.test');
define('MAIL_FROM_NAME', 'PharmaSync');

/* ==========================================================================
   8. Environment
   ==========================================================================
   'dev'  -> errors shown on screen
   'prod' -> errors written to the log only. Set this before the final demo.
*/
define('APP_ENV', 'dev');

if (APP_ENV === 'dev') {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
} else {
    error_reporting(E_ALL);
    ini_set('display_errors', '0');
    ini_set('log_errors', '1');
}

/* ==========================================================================
   9. Session cookie + start
   ========================================================================== */
if (session_status() === PHP_SESSION_NONE) {
    session_set_cookie_params([
        'httponly' => true,
        'samesite' => 'Lax',
        'secure'   => !empty($_SERVER['HTTPS']),
        'path'     => '/',
    ]);
    session_start();
}

require_once CONFIG_PATH . '/helpers.php';
